services:
  - type: web
    name: golf-leaderboard
    env: python
    buildCommand: ./render_build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DATABASE_URL
        fromDatabase:
          name: golf_leaderboard_db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true
    plan: free
    healthCheckTimeout: 300
    healthCheckInterval: 30 