services:
  - type: web
    name: golf-leaderboard
    env: python
    buildCommand: ./render_build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DATABASE_URL
        fromDatabase:
          name: golf_leaderboard_db
          property: connectionString
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    plan: free
    healthCheckTimeout: 300
    healthCheckInterval: 30 